// src/app/layout.tsx
import type { Metadata } from 'next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import './globals.css'

// Importa o componente cliente que terá o <Toaster />
import { ToasterClient } from '@/components/ui/toast/toaster-client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="pt-BR">
      <head />
      <body suppressHydrationWarning>
        {/* Componente client que possui <Toaster /> */}
        <ToasterClient />

        {/* Restante da aplicação */}
        {children}

        {/* SpeedInsights (somente no client side, se quiser manter) */}
        {typeof window !== 'undefined' && <SpeedInsights />}
      </body>
    </html>
  )
}
