import type { Metadata } from 'next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { ToasterClient } from '@/components/ui/toast/toaster-client'
import { ToastProvider } from '@/components/ui/toast/toast'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="pt-BR">
      <head />
      <body suppressHydrationWarning>
        <ToastProvider>
          <ToasterClient />
          {children}
        </ToastProvider>
        {typeof window !== 'undefined' && <SpeedInsights />}
      </body>
    </html>
  )
}
